version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"

phases:
  install:
    commands:
        - echo "Deployment Stage"
        - ls
        - mv download/terraform /usr/local/bin/
        - terraform -version
  pre_build:
    commands:
      - cd bootstrap
      - terraform init
      - terraform plan -var="region=${AWS_REGION}" -out tf.plan
  build:
    commands:
      - terraform apply tf.plan
  post_build:
    commands:
      - terraform destroy -var="region=${AWS_REGION}" -auto-approve
    # finally:
    #   - command
    #   - command
artifacts:
  files:
      - bootstrap/bootstrap.tf
      - bootstrap/terraform.tfstate
      
#     - buildspec_integration.yml
#     - buildspec_tagging.yml
#     - convergdb-*-java.gem
#     - src.jar
#     - bin/*
#     - test/fixtures/bin/*
#     - test/fixtures/integration_test_*/**/*

