version: 0.2

env:
  variables:
    TF_VERSION: "0.12.28"
    CONVERGDB_ENV_NAME: "dev"

phases:
  install:
    commands:
      - mkdir download && cd download
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - cd ..
  pre_build:
    commands:
      - git clone https://github.com/beyondsoft-na/convergdb.git
      - cp convergdb/convergdb.jar .
  build:
    commands:
      - java -jar convergdb.jar generate
      - ls
artifacts:
  files:
      - buildspec_deployment.yml
      - download/terraform
      - terraform/**/*
      - backend.tf
      - variables.tf
      - '*.tfvars'
