version: 0.2

env:
  variables:
    # AWS_REGION: "us-west-2"
    CONVERGDB_ENV_NAME: "dev"

phases:
  install:
    commands:
        - echo "Deployment Stage"
        - ls
        - mv download/terraform /usr/local/bin/
        - terraform -version
        - echo "output test"
        - echo "${CONVERGDB_ENV_NAME}.tfvars"
        - cat ${CONVERGDB_ENV_NAME}.tfvars
        - export AWS_REGION=`awk '/region/{print $NF}' ${CONVERGDB_ENV_NAME}.tfvars | sed 's/"//g'`
        - echo $AWS_REGION
        - export CONVERGDB_DEPLOYMENT_ID=`awk '/deployment_id/{print $NF}' ${CONVERGDB_ENV_NAME}.tfvars | sed 's/"//g'` 
        - echo $CONVERGDB_DEPLOYMENT_ID
  pre_build:
    commands:
      - mv backend.tf terraform/
      - mv *.tfvars terraform/
      - mv variables.tf terraform/
      - ls terraform/
  build:
    commands:
      - cd terraform
      - terraform init -backend-config="bucket=convergdb-admin-${CONVERGDB_DEPLOYMENT_ID}" -backend-config="key=terraform/convergdb.tfstate" -backend-config="dynamodb_table=convergdb-lock-${CONVERGDB_DEPLOYMENT_ID}" -backend-config="region=${AWS_REGION}"
      - terraform plan -var-file="${CONVERGDB_ENV_NAME}.tfvars" -out tf.plan
      # - terraform apply tf.plan
  # post_build:
  #   commands:
  #     - terraform destroy -auto-approve
  #     - cd ../bootstrap
  #     - terraform destroy -var="region=${AWS_REGION}" -auto-approve

artifacts:
  files:
      # - bootstrap/bootstrap.tf
      # - bootstrap/terraform.tfstate
      - terraform/**/*


#     - buildspec_integration.yml
#     - buildspec_tagging.yml
#     - convergdb-*-java.gem
#     - src.jar
#     - bin/*
#     - test/fixtures/bin/*
#     - test/fixtures/integration_test_*/**/*

