version: 0.2

env:
  variables:
    CONVERGDB_ENV_NAME: "prod"
    BACKEND_BUCKET: "convergdb-admin"
    BACKEND_PROFIX: "terraform/convergdb.tfstate"
    BACKEND_DYNAMODB_LOCK_TABLE: "convergdb-lock"

  secrets-manager:
    key: convergdb-stage-keys:aws_access_key_id_${CONVERGDB_ENV_NAME}
    value: convergdb-stage-keys:aws_secret_access_key_${CONVERGDB_ENV_NAME}

phases:
  install:
    commands:
        - export AWS_ACCESS_KEY_ID=$key
        - export AWS_SECRET_ACCESS_KEY=$value
        - ls
        - mv download/terraform /usr/local/bin/
        - terraform -version
        - echo "output test"
        - echo "${CONVERGDB_ENV_NAME}.tfvars"
        - cat ${CONVERGDB_ENV_NAME}.tfvars
        - export AWS_REGION=`awk '/region/{print $NF}' ${CONVERGDB_ENV_NAME}.tfvars | sed 's/"//g'`
        - echo $AWS_REGION
        - export CONVERGDB_DEPLOYMENT_ID=`awk '/deployment_id/{print $NF}' ${CONVERGDB_ENV_NAME}.tfvars | sed 's/"//g'` 
        - echo $CONVERGDB_DEPLOYMENT_ID
  pre_build:
    commands:
      - mv backend.tf terraform/
      - mv *.tfvars terraform/
      - mv variables.tf terraform/
      - ls terraform/
  build:
    commands:
      - cd terraform
      - cat ${CONVERGDB_ENV_NAME}.tfvars
      - terraform init -backend-config="bucket=${BACKEND_BUCKET}-${CONVERGDB_DEPLOYMENT_ID}" -backend-config="key=${BACKEND_PROFIX}" -backend-config="dynamodb_table=${BACKEND_DYNAMODB_LOCK_TABLE}-${CONVERGDB_DEPLOYMENT_ID}" -backend-config="region=${AWS_REGION}"
      - terraform plan -var-file="${CONVERGDB_ENV_NAME}.tfvars" -out tf.plan
      - terraform apply tf.plan
  post_build:
    commands:
      - terraform destroy -var-file="${CONVERGDB_ENV_NAME}.tfvars" -auto-approve


artifacts:
  files:
      - terraform/**/*

