version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/beyondsoft-na/convergdb.git
      - mv convergdb/convergdb.jar .
      - ls
  pre_build:
    commands:
      - java -jar convergdb.jar generate
      - ls
#   build:
#     commands:
#       - bundle exec gem build convergdb.gemspec
#       - warble
# artifacts:
#   files:
#     - buildspec_integration.yml
#     - buildspec_tagging.yml
#     - convergdb-*-java.gem
#     - src.jar
#     - bin/*
#     - test/fixtures/bin/*
#     - test/fixtures/integration_test_*/**/*

